name: Build & Test

on: [push]

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        destination: [
          'iOS Simulator,OS=16.0,name=iPhone 8',
#           'macOS',
#           'watchOS Simulator,name=Apple Watch Series 6 - 44mm'
        ]
    steps:
    - uses: actions/checkout@v2    
    - name: Build
      run: xcodebuild build -destination 'platform=${{ matrix.destination }}' -scheme 'TjekSDK' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run Tests
      run: xcodebuild test -destination 'platform=${{ matrix.destination }}' -scheme 'TjekSDK' | xcpretty && exit ${PIPESTATUS[0]}
