name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: [
          'iOS Simulator,OS=13.7,name=iPhone 8',
          'iOS Simulator,OS=15.2,name=iPhone 13'
        ]
    steps:
    - uses: actions/checkout@v2    
    - name: Build
      run: xcodebuild build -destination 'platform=${{ matrix.destination }}' -scheme 'TjekSDK' | xcpretty
    - name: Run Tests
      run: xcodebuild test -destination 'platform=${{ matrix.destination }}' -scheme 'TjekSDK' | xcpretty
